### ISSUE TITLE
Mod features don't work

### ISSUE THREAD

**Issue by RyanCR03** [SrGnis/Creeper_AI_Updated#5]
Mod-menu says cau is in the mod list and config file is generated but none of the features work and it is just the default creeper ai.

Minecraft version 1.16.4

Fabric version 0.11.2

Mod version 1.3.2

triggered crash via f3+c

https://pastebin.com/M1uQCjB4

**Comment by SrGnis** [comment]
I see that you are using several mods, just to be sure, If you use only my mod it works?

**Comment by RyanCR03** [comment]
incompatible with multiple mods, it will probably take years of trial and error to see what mods don't work

**Comment by SrGnis** [comment]
Ok, I will take a look to the mod list and try to find  the cause of the incompatibility, but as you say it will took a long time. If you discover anything post it here.

**Comment by SrGnis** [comment]
This seems the same problem as issue #7, it is solved in #8 and the version 1.3.3

**Comment by SrGnis** [comment]
This seems the same problem as issue #7, it is solved in #8 and the version 1.3.3
