### ISSUE TITLE
Incompatibility with Chroma Blocks

### ISSUE THREAD

**Issue by Wpgradford** [SrGnis/Creeper_AI_Updated#7]
For some reason, when these two mods are used together, [Chroma Blocks](https://www.curseforge.com/minecraft/mc-mods/chroma-concrete) always takes priority and overrides Creeper AI Updated

**Comment by SrGnis** [comment]
Hi I tested the two mods and work perfectly together.

Here are the versions I am using:

 -Creeper AI Updated 1.3.2
 -Chroma Blocks 1.1.0
 -Fabric Loader 0.11.2
 -Fabric API 0.31.0

**Comment by Wpgradford** [comment]
Huh... same here. Only difference is that I'm using Fabric Loader 0.11.1, but it works fine when they're alone. I'll test around a bit with my other mods and see if it's somehow an entirely different mod making the two incompatible.

EDIT: I've been working at figuring out what the compatibilities are for a little over 2 hours, but it's just getting a little too confusing and I'm sure someone who can look through the code can figure it out better than I can. 

Here are the "incompatible" mods, ran with Fabric Loader 0.11.2 and Fabric API 0.31.0:
-[Curios API 0.0.13](https://www.curseforge.com/minecraft/mc-mods/curios-fabric/files/3233941) (FIXES INCOMPATIBILITY WHEN REMOVED)
-[Fireplace Lib 3.1.0](https://www.curseforge.com/minecraft/mc-mods/fireplace-lib/files/3228725) (FIXES INCOMPATIBILITY WHEN REMOVED)
-[Not Enough Crashes 3.1.8](https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes/files/3226331) (FIXES INCOMPATIBILITY WHEN REMOVED)
-[Fabric Language Kotlin 1.5.0 1.4.31](https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin/files/3225502) (FIXES INCOMPATIBILITY WHEN REMOVED)
-[GeckoLib 3.0.23](https://www.curseforge.com/minecraft/mc-mods/geckolib-fabric/files/3224450) (FIXES INCOMPATIBILITY WHEN REMOVED)
-[Bamboo Tweaks 2.0.0](https://www.curseforge.com/minecraft/mc-mods/bamboo-tweaks-fabric/files/2989935) (FIXES INCOMPATIBILITY WHEN REMOVED)
-[Library of Exile 1.0.6](https://www.curseforge.com/minecraft/mc-mods/library-of-exile/files/3094450) (FIXES INCOMPATIBILITY WHEN REMOVED)
-[FlytreLib 0.2.8](https://www.curseforge.com/minecraft/mc-mods/flytrelib/files/3219033) (FIXES INCOMPATIBILITY WHEN REMOVED)
-[YUNG's Better Caves 1.1](https://www.curseforge.com/minecraft/mc-mods/yungs-better-caves-fabric/files/3218659) (FIXES INCOMPATIBILITY WHEN REMOVED)
-[YUNG's API 2](https://www.curseforge.com/minecraft/mc-mods/yungs-api-fabric/files/3218648) (YUNG's Better Caves relies on this, so it's impossible to remove without removing both, but I suspect it's fixes the incompatibility when removed)
-[Celib 0.3.1](https://www.curseforge.com/minecraft/mc-mods/celib/files/3208890) (FIXES INCOMPATIBILITY WHEN REMOVED)
-[Draylar's Battle Towers 3.3.3](https://www.curseforge.com/minecraft/mc-mods/draylars-battle-towers/files/3210181) (FIXES INCOMPATIBILITY WHEN REMOVED)
-[Mod Menu 1.16.8](https://www.curseforge.com/minecraft/mc-mods/modmenu/files/3211066) (causes a crash when removed)
-[Dawn API 1.7](https://www.curseforge.com/minecraft/mc-mods/dawn/files/3213550) (FIXES INCOMPATIBILITY WHEN REMOVED)
-[Lithium 0.6.4](https://www.curseforge.com/minecraft/mc-mods/lithium/files/3215441) (FIXES INCOMPATIBILITY WHEN REMOVED)
-[Chromatic Blocks 1.1.0](https://www.curseforge.com/minecraft/mc-mods/chroma-concrete/files/3204542) (FIXES INCOMPATIBILITY WHEN REMOVED)
-[TRansliterationLib 1.0.2](https://www.curseforge.com/minecraft/mc-mods/transliterationlib/files/3205080) (FIXES INCOMPATIBILITY WHEN REMOVED)
-[Phosphor 0.7.1 Build 11](https://www.curseforge.com/minecraft/mc-mods/phosphor/files/3202749) (FIXES INCOMPATIBILITY WHEN REMOVED)
-[Better Beds 1.1.0](https://www.curseforge.com/minecraft/mc-mods/better-beds/files/3196688) (FIXES INCOMPATIBILITY WHEN REMOVED)
-[Banner Capes 0.2.1](https://www.curseforge.com/minecraft/mc-mods/banner-capes/files/3002310) (FIXES INCOMPATIBILITY WHEN REMOVED)
-[Sodium 0.1.0](https://www.curseforge.com/minecraft/mc-mods/sodium/files/3067101) (FIXES INCOMPATIBILITY WHEN REMOVED)
-[Blame 2.4.1](https://www.curseforge.com/minecraft/mc-mods/blame-fabric/files/3181315) (FIXES INCOMPATIBILITY WHEN REMOVED)
-[Data Loader 2.0.1](https://www.curseforge.com/minecraft/mc-mods/data-loader/files/2989927) (FIXES INCOMPATIBILITY WHEN REMOVED)
-[MixinTrace 1.0.0](https://www.curseforge.com/minecraft/mc-mods/mixintrace/files/3157660) (FIXES INCOMPATIBILITY WHEN REMOVED)
-[Trinkets 2.6.7](https://www.curseforge.com/minecraft/mc-mods/trinkets-fabric/files/3100959) (Banner Capes relies on this, so it's impossible to remove without removing both, but I suspect it's fixes the incompatibility when removed)
-[Better Dropped Items 1.2.4](https://www.curseforge.com/minecraft/mc-mods/better-dropped-items/files/3108108) (FIXES INCOMPATIBILITY WHEN REMOVED)

Here are mods I first suspected were incompatible, but the incompatibility persisted after I removed:
-[Cloth Config API 4.11.14](https://www.curseforge.com/minecraft/mc-mods/cloth-config/files/3210410)

**Comment by SrGnis** [comment]
Thank you very much for collecting this list of incompatibilities. I will start to investigate what is the problem that is causing it.

**Comment by SrGnis** [comment]
It seems that it is not a compatibility problem, the problem is that, for some reason, when the mod count reaches 99 the CAU mixins stop working. I have verified this by adding another mod to the list making a total of 100 mods so when a mod is removed it still does not work, except for some mods that count as several instead of one.

I will still working in this issue.
